- name: "install python."
  apt:
    name: python
    state: present
    update_cache: true

- name: "Updates apt cache"
  apt:
    update_cache: yes

- name: "Install NodeJs"
  become: true
  shell: |
    apt -y upgrade
    apt install -y nodejs
    apt install -y npm

- name: "Install pm2"
  become: true
  shell: |
    npm install pm2 -g
