- name: Upgrade packages
  become: true
  apt: 
   update_cache: yes

- name: Install tar,gzip && gunzip
  become: true
  apt:
    name: '{{ item }}'
    update_cache: yes
  with_items: 
    - tar
    - gzip
    - gunzip

- name: "Creates new directory for backend"
  file:
    path: ~/app
    state: directory

- name: "Copy build archive"
  copy:
    src: artifact.tar.gz
    dest: "~/app/artifact.tar.gz"

- name: "Unzip build archive"
  shell: |
    cd ~/app
    tar -xvzf artifact.tar.gz
    
- name: Install node dependencies
  command: npm i 
  args:
    chdir: ~/backend-app

- name: Start app
  command:  pm2 start main.js
  args:
    chdir: ~/backend-app/dist
  

  environment:
    ENVIRONMENT: "production"
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
